server:
  port: 9999

#zuul:
#  routes:
#    bankslip:
#      path: /bankslip/**
#      stripPrefix: false
#    card:
#      path: /card/**
#      stripPrefix: false
#      serviceId: card
#    electronictransfer:
#      path: /electronictransfer/**
#      stripPrefix: false
#      serviceId: electronictransfer
eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: false
    ip-address: ${IP_HOST:${HOSTNAME}}
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost:8761}/eureka/
      
---
spring:
  profiles: prod

url:
  intencao: https://gate.2all.com.br/gateway/intencao/pagamento
  tokenizacao: https://gate.2all.com.br/gateway/intencao/salvarCartao
