server:
   port: ${BANKSLIP_PORT:8082}

spring:
  profiles:
    active: docker
  cloud:
    config:
      uri: http://${CONFIG_SERVER:localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost:8761}/eureka/
  instance:
    ip-address: {IP_HOST}
