server:
   port: ${BANKSLIP_PORT:8082}

spring:
  profiles:
    active: docker

spring:
  cloud:
    config:
      uri: http://${config-service:localhost}:8888

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-service:localhost}:8761/eureka/