server:
   port: ${BANKSLIP_PORT:8082}

spring:
  profiles:
    active: docker
  cloud:
    config:
      uri: http://${configserviceaa}:8888

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaservice:localhost}:8761/eureka/
