server:
   port: ${CARD_PORT:8080}

spring:
  profiles:
    active: docker
  cloud:
    config:
      uri: http://${configservice:localhost}:8888

eureka:
  client:
    service-url:
      defaultZone: http://${eurekaservice:localhost}:8761/eureka/
