server:
   port: ${CARD_PORT:8080}
---
spring:
  profiles:
    active: default
hostname: ${HOSTNAME:localhost}
maxSize: 20

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://${CONFIG_SERVER:localhost:8888}

eureka:
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER:localhost:8761}/eureka/
