eureka:
  instance:
    hostname: configservice
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eurekaservice:localhost}:8761/eureka/







