eureka:
  instance:
    hostname: configservice
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaservice:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rsxo/config-server