server:
  port: ${ELECTRONIC_TRANSFER:8081}

spring:
  profiles:
    active: docker
  cloud:
    config:
      uri: http://${config-service:localhost}:8888

eureka:
  client:
    service-url:
      defaultZone: http://${eureka-service:localhost}:8761/eureka/
